### ISSUE TITLE
Use of "add_stylesheet()" causes Sphinx >=4.0 to fail

### ISSUE THREAD

**Issue by andy-maier** [Smile-SA/sphinx-versions#12]
Sphinx 4.0 has removed the `Sphinx.add_stylesheet()` method that was deprecated since Sphinx 1.8.
See also https://github.com/sphinx-doc/sphinx/issues/7747.

Python 3.10 requires Sphinx >=4.2, so this problem also prevents using sphinx-versions on Python 3.10.

Here is how it fails (e.g. from [this log](https://github.com/zhmcclient/zhmc-ansible-modules/runs/4520807795?check_suite_focus=true#step:11:40)):

```
Running Sphinx v4.2.0

Exception occurred:
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/sphinxcontrib/versioning/sphinx_.py", line 156, in setup
    app.add_stylesheet('banner.css')
AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'
The full traceback has been saved in /tmp/sphinx-err-cy6e51wu.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Process Process-2:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/sphinxcontrib/versioning/sphinx_.py", line 210, in _build
    raise SphinxError
sphinx.errors.SphinxError
```

Please change to using the recommended replacement function in sphinx-versions.

I verified this with sphinx-versions 1.0.0 and 1.1.3, and with Sphinx 4.2.0 and 4.3.1 (on Python 3.10 on macOS).

**Comment by riebecj** [comment]
I've submitted #16 which should fix this, but I have to wait for maintainers to approve and merge. Until then, you can use my fork which includes the fixes via:
```bash
pip3 install git+https://github.com/riebecj/sphinx-versions.git
```

**Comment by andy-maier** [comment]
Hi @riebecj thanks for the fix. See #13 on the maintaintership. If and when the transition happens, I'll work through your PR to integrate it.
