### ISSUE TITLE
rtd theme crashes

### ISSUE THREAD

**Issue by WimYedema** [Smile-SA/sphinx-versions#4]
Using the sphinx-rtd-theme crashes in `pathtopdf`

```
Traceback (most recent call last):
  File "c:\users\yedema21\git\flow\venv\lib\site-packages\sphinx\builders\html.py", line 1027, in handle_page
    output = self.templates.render(templatename, ctx)
  File "c:\users\yedema21\git\flow\venv\lib\site-packages\sphinx\jinja2glue.py", line 207, in render
    return self.environment.get_template(template).render(context)
  File "c:\users\yedema21\git\flow\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\yedema21\git\flow\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\yedema21\git\flow\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\yedema21\git\flow\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "c:\users\yedema21\git\flow\venv\lib\site-packages\sphinx\themes\basic\page.html", line 10, in <module>
    {%- extends "layout.html" %}
  File "c:\users\yedema21\git\flow\venv\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "c:\users\yedema21\git\flow\venv\lib\site-packages\sphinx\themes\basic\page.html", line 14, in root
  File "c:\users\yedema21\git\flow\venv\lib\site-packages\sphinx_rtd_theme\layout.html", line 179, in root
    <div class="wy-nav-content">
  File "c:\users\yedema21\git\flow\venv\lib\site-packages\sphinxcontrib\versioning\_templates\versions.html", line 19, in root
    <dt>Branches</dt>
  File "c:\users\yedema21\git\flow\venv\lib\site-packages\jinja2\sandbox.py", line 387, in getattr
    value = getattr(obj, attribute)
  File "c:\users\yedema21\git\flow\venv\lib\site-packages\sphinxcontrib\versioning\versions.py", line 205, in tags
    return [(r['name'], self.vpathto(r['name']), self.pathtopdf(r['name'])) for r in self.remotes if r['kind'] == 'tags']
  File "c:\users\yedema21\git\flow\venv\lib\site-packages\sphinxcontrib\versioning\versions.py", line 205, in <listcomp>
    return [(r['name'], self.vpathto(r['name']), self.pathtopdf(r['name'])) for r in self.remotes if r['kind'] == 'tags']
  File "c:\users\yedema21\git\flow\venv\lib\site-packages\sphinxcontrib\versioning\versions.py", line 256, in pathtopdf
    components += [os.path.splitext(self.pdf_file)[0]]
  File "C:\Users\yedema21\AppData\Local\Programs\Python\Python38\lib\ntpath.py", line 196, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\yedema21\git\flow\venv\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "c:\users\yedema21\git\flow\venv\lib\site-packages\sphinx\application.py", line 353, in build
    self.builder.build_update()
  File "c:\users\yedema21\git\flow\venv\lib\site-packages\sphinx\builders\__init__.py", line 297, in build_update
    self.build(to_build,
  File "c:\users\yedema21\git\flow\venv\lib\site-packages\sphinx\builders\__init__.py", line 361, in build
    self.write(docnames, list(updated_docnames), method)
  File "c:\users\yedema21\git\flow\venv\lib\site-packages\sphinx\builders\__init__.py", line 535, in write
    self._write_serial(sorted(docnames))
  File "c:\users\yedema21\git\flow\venv\lib\site-packages\sphinx\builders\__init__.py", line 545, in _write_serial
    self.write_doc(docname, doctree)
  File "c:\users\yedema21\git\flow\venv\lib\site-packages\sphinx\builders\html.py", line 622, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "c:\users\yedema21\git\flow\venv\lib\site-packages\sphinx\builders\html.py", line 1034, in handle_page
    raise ThemeError(__("An error happened in rendering the page %s.\nReason: %r") %
sphinx.errors.ThemeError: An error happened in rendering the page api/flow.
Reason: TypeError('expected str, bytes or os.PathLike object, not NoneType')

Theme error:
An error happened in rendering the page api/flow.
Reason: TypeError('expected str, bytes or os.PathLike object, not NoneType')
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\yedema21\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 313, in _bootstrap
    self.run()
  File "C:\Users\yedema21\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\yedema21\git\flow\venv\lib\site-packages\sphinxcontrib\versioning\sphinx_.py", line 213, in _build
    raise SphinxError
sphinx.errors.SphinxError
=> sphinx-build failed for branch/tag: master

```

**Comment by WimYedema** [comment]
Version 1.0.1 works fine. Haven't tried other versions

**Comment by dryobates** [comment]
> Version 1.0.1 works fine. Haven't tried other versions

I did. 1.0.1 is the latest working one. I also tried #5. Works for me.

**Comment by WqyJh** [comment]
Same problem. #5 works, please release it in new version.
